apiVersion: v1
kind: Secret
metadata:
  name: eszop-secrets
type: Opaque
data:
  ESZOP_SQLSERVER_CONN_STR_IDENTITY: PLACE_HOLDER
  ESZOP_AZURE_STORAGE_CONN_STR: PLACE_HOLDER
  ESZOP_AZURE_EVENTBUS_CONN_STR: PLACE_HOLDER
  ESZOP_REDIS_CONN_STR: PLACE_HOLDER
  ESZOP_SQLSERVER_CONN_STR_CARTS: PLACE_HOLDER
  ESZOP_SQLSERVER_CONN_STR_OFFERS: PLACE_HOLDER
  ESZOP_SQLSERVER_CONN_STR_NOTIFICATION: PLACE_HOLDER
  ESZOP_SQLSERVER_CONN_STR_ORDERS: PLACE_HOLDER

