apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: eszop-selfsigned
spec:
  secretName: eszop-selfsigned
  isCA: true
  issuerRef:
    name: selfsigning-issuer
    kind: ClusterIssuer