apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  selector:
    matchLabels:
      app: apigateway
  replicas: 1
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: eszopregistry.azurecr.io/eszop-api-gateway:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
            - name: ASPNETCORE_URLS
              value: http://+
            - name: ESZOP_LOGS_DIR
              value: /logs
            - name: ESZOP_CLIENT_URI
              valueFrom:
                configMapKeyRef:
                  key: ESZOP_CLIENT_URI
                  name: eszop-config
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthcheck
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: eszop-api-gateway
spec:
  selector:
    app: apigateway
  ports:
    - port: 80
      targetPort: 80
