apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: eszopregistry.azurecr.io/eszop-frontend:latest
          imagePullPolicy: Always
          env:
          - name: ESZOP_API_URL
            valueFrom:
              configMapKeyRef:
                key: ESZOP_API_URL
                name: eszop-config
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
              name: api
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: eszop-frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      name: api
