apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
spec:
  selector:
    matchLabels:
      app: identity
  replicas: 1
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
        - name: identity
          image: eszopregistry.azurecr.io/eszop-identity-api:latest
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
            - name: ASPNETCORE_URLS
              value: http://+
            - name: ESZOP_LOGS_DIR
              value: /logs
            - name: ESZOP_SQLSERVER_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: ESZOP_SQLSERVER_CONN_STR_IDENTITY
            - name: ESZOP_AZURE_EVENTBUS_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: ESZOP_AZURE_EVENTBUS_CONN_STR
            - name: ESZOP_REDIS_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: ESZOP_REDIS_CONN_STR
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
              name: api
            - containerPort: 8080
              name: grpc
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: identity-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: identity
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: eszop-identity-api
spec:
  selector:
    app: identity
  ports:
    - port: 80
      targetPort: 80
      name: api
