apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
spec:
  selector:
    matchLabels:
      app: carts
  replicas: 1
  template:
    metadata:
      labels:
        app: carts
    spec:
      containers:
        - name: carts
          image: eszopregistry.azurecr.io/eszop-carts-api:latest
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: ASPNETCORE_ENVIRONMENT
                  name: eszop-config
            - name: ASPNETCORE_URLS
              value: http://+
            - name: ESZOP_LOGS_DIR
              value: /logs
            - name: ESZOP_SQLSERVER_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: eszop-secrets
                  key: ESZOP_SQLSERVER_CONN_STR_CARTS
            - name: ESZOP_AZURE_EVENTBUS_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: eszop-secrets
                  key: ESZOP_AZURE_EVENTBUS_CONN_STR
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
              name: api
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthcheck
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 10
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: carts-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: carts
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: eszop-carts-api
spec:
  selector:
    app: carts
  ports:
    - port: 80
      targetPort: 80
      name: api
