SQLSERVER_USERNAME: "[PROVIDE VALUE]"
SQLSERVER_PASSWORD: "[PROVIDE VALUE]"
SQLSERVER_CONN_STR_TEMPLATE: "[PROVIDE VALUE]"
REDIS_ADDRESS: "[PROVIDE VALUE]"
REDIS_PORT: "[PROVIDE VALUE]"
REDIS_PASSWORD: "[PROVIDE VALUE]"
AZURE_STORAGE_CONN_STR: "[PROVIDE VALUE]"
AZURE_EVENTBUS_CONN_STR: "[PROVIDE VALUE]"