VM_BASED_DOMAIN_NAME: "[PROVIDE VALUE]"
CONTAINER_BASED_DOMAIN_NAME: "[PROVIDE VALUE]"
SQLSERVER_USERNAME: "[PROVIDE VALUE]"
SQLSERVER_PASSWORD: "[PROVIDE VALUE]"
REDIS_ADDRESS: "[PROVIDE VALUE]"
REDIS_PORT: "[PROVIDE VALUE]"
REDIS_PASSWORD: "[PROVIDE VALUE]"
ESZOP_AZURE_STORAGE_CONN_STR: "[PROVIDE VALUE]"
ESZOP_AZURE_EVENTBUS_CONN_STR: "[PROVIDE VALUE]"
ESZOP_SQLSERVER_CONN_STR_TEMPLATE: "[PROVIDE VALUE]"